services:

  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:8.0.29
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_DATABASE=onlyoffice
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
     - ./config/mysql/conf.d:/etc/mysql/conf.d
     - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - ./mysql_data:/var/lib/mysql

  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:latest
    depends_on:
     - onlyoffice-mysql-server
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
     - MYSQL_SERVER_DB_NAME=onlyoffice
     - MYSQL_SERVER_HOST=onlyoffice-mysql-server
     - MYSQL_SERVER_USER=onlyoffice_user
     - MYSQL_SERVER_PASS=onlyoffice_pass
    ports:
     - '8100:80'
     - '8443:443'
     - '5222:5222'
    stdin_open: true
    tty: true
    restart: unless-stopped
    privileged: true
    cgroup: host
    volumes:
     - ./community_data:/var/www/onlyoffice/Data
     - ./community_log:/var/log/onlyoffice
     - ./document_data:/var/www/onlyoffice/DocumentServerData
     - /sys/fs/cgroup:/sys/fs/cgroup:rw
